return lowerkeys({
gDecal = {
	alwaysvisible		= true,
	name				= "Geothermal Vent",
	blocking			= false,
	category			= "geothermal",
	collisionVolumeType	="box",
	collisionVolumeScales={30, 3, 30},
	collisionVolumeOffsets={0, 0, 0},
	damage				= 1800,
	description			= "Can be a source of energy.",
	energy				= 0,
	flammable			= 0,
	footprintX			= 6,
	footprintZ			= 6,
	height				= "5",
	hitdensity			= "0",
	indestructible 			= true,
	metal				= 0,
	crushresistance		= 300,
	reclaimable			= false,
	autoreclaimable			= false, 	
	world				= "All Worlds",
	useBuildingGroundDecal =true,
	buildingGroundDecalType = "_geodecal.dds",
	buildingGroundDecalSizeX = 6,
	buildingGroundDecalSizeY = 6,
}
})
